# Generated by Django 4.2.21 on 2025-05-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image File'), ('TEXT', 'Plain Text')], default='TEXT', help_text='Type of the document (e.g., PDF, Image, Plain Text).', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Uploaded PDF or image file.', null=True, upload_to='medical_documents/')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text content from user input or OCR extraction.', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAssistantInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_query', models.TextField(help_text='The initial query or context provided by the user that triggered the analysis.')),
                ('extracted_context_summary', models.JSONField(blank=True, help_text='Summary of historical data points used in this specific interaction.', null=True)),
                ('reasoning_output', models.TextField(help_text='The raw analysis output from the Reasoning Model Agent.')),
                ('final_analysis', models.TextField(help_text='The final, refined analysis output from the Revisor Agent, presented to the user.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedMedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test Results'), ('DIAGNOSIS', 'Diagnosis'), ('MEDICATION', 'Medication List'), ('SYMPTOMS', 'Symptoms Description'), ('OTHER', 'Other Medical Information')], default='OTHER', help_text='Type of extracted medical data.', max_length=20)),
                ('extracted_json', models.JSONField(help_text='Structured medical data in JSON format.')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(blank=True, help_text='Link to the original MedicalDocument this data was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medassist.medicaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_medical_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
